stages:
    - deploy
deploy:
    stage: deploy
    script:
        - echo "发布中...."
        - sudo cp -fr extension/custom/* /opt/zentaopms/extension/custom/
        - echo "发布完成"
    only:
        - master